### PR TITLE
protocol 1 fixes

### PR DESCRIPTION
**Pull request by pavel-demin**
Hello Richie,

Would you be interested in adding these changes to your version of Thetis?

These fixes have been tested by a few radio operators and found to be helpful.

Best regards,

Pavel

### CODE REVIEW

**Comment by ramdor** [comment]
I've talked to Doug about some of these changes in the last version Pavel, specifically the sample rate change, and the changes to the DDC's.  I will forward this merge request to him for him to check.

Regarding the 31dB if tx'ing in P1, I don't know if this is a requirement of existing anan hardware running P1, not sure. Interesting that the 0b00011111 bitmask is missing on C1 assignment if not tx'ing though.

As far as the PS rate change, afaik PS always needs to run at 192000 (mentioned by Warren a number of times), and if you look at updateddc function in console.cs ddc0 and ddc1 will be set to ps_rate. I am not sure changing ps_rate is a good idea until it has been looked at by Doug/Warren.

Richie.

**Comment by pavel-demin** [comment]
Thank you for looking at these changes.

> As far as the PS rate change, afaik PS always needs to run at 192000 (mentioned by Warren a number of times)

My interpretation of this requirement is that 192000 is the minimum sample rate that works well for PS. So, in my understanding, the requirement is that PS needs to run at **at least** 192000.

In protocol 1, all receivers operate at the same rate. Different rates for PS and other receivers are therefore not supported by Protocol 1. That is why I had to change the PS sample rate in the protocol 1 code.

**Comment by ramdor** [comment]
Hi Pavel, I have had a reply from Warren, and looks like a **no** on the sample rates/ddc change/ps_rate change. I will wait to hear on the attenuation issue. Quote :

> * enable 384K sample rate for protocol 1:  The reason this wasn't done is that the 1Mbit ethernet doesn't have enough bandwidth to support several configs, particularly those using PureSignal.  Hence, to simplify and avoid confusion and endless bug reports, we limited to 192K.
> 
> * fix UpdateDDCs:  It's fine as it is now, in fact, what he proposes would introduce a bug.  Just looking down through it --
>    - one could eliminate the assignments to P1_DDCConfig ... I don't think those values are actually used anywhere
>    - he proposes adding some assignments to Rate[0], Rate[1], and Rate[2] ... that is both unnecessary and I think confusing.  It's confusing because those rates are not being used at all in the cases he proposes assignments, so, how were these values determined?
>    - finally, in one place he proposes changing Rate[1] from rx2_rate to rx1_rate which would introduce a bug.
> 
> * on the PureSignal sample-rates, it limps along at other rates; however, it is really set up only for 192K.  I opened it up in the application to multiple rates at one point and then decided I needed to restrict it to just 192K for now.  In the future, I may support some other rates.  It's unlikely I'll ever support 48K or 96K - for solid technical reasons.  However, I'm likely to support higher rates, especially 768K and 1536K, at some point.

To continue on,

Regarding the PTT delay, did you time the disable of the band buttons? Both disable and enable came out at ~11ms in debug mode. I don't see how removing that changes the ptt to ant select delay, as they both happen after in HdwMOXChanged().

I ran some more timing analysis from 

`if (tx)                     // change to TX mode`

and just after the else to the end of the function, which encompasses all antenna selection, ptt relay changes etc etc. 

MOX on = ~58ms, MOX off = ~77ms

commenting out this code had no impact in these timings. However, that said, it is completely redundant anyway, and duplicated, as it is performed in UIMOXChangedTrue/UIMOXChangedFalse, so will be removed as you suggest from chkMOX_CheckedChanged2(), but has no impact on the att/ptt delay. The 11ms has an impact in the MOXon to MOXoff delay however.

Thanks, Richie.

**Comment by pavel-demin** [comment]
> Hence, to simplify and avoid confusion and endless bug reports, we limited to 192K.

Thank you for the clarification. 

I made these changes because some radio operators using my applications for the Red Pitaya board asked me to make them. Since these changes worked for them, I was curious to try pushing them to the main version of Thetis.

It is good to know that the 384k sample rate for protocol 1 in Thetis has been disabled for a reason and there is no intention to re-enable it. Maybe for better compatibility with Thetis I will disable this sample rate in my applications for the Red Pitaya board.

> Regarding the PTT delay,...

When I did my tests I measured the delay between the pressing of a CW key attached to the board and the arrival of antenna switching commands from Thetis to the board. I expected the delay to be less than 10 ms but I was surprised to see that Thetis spent time doing low priority things like GUI redrawing before sending the commands to the board that I consider high priority task for a control system like this. The only simple way to reduce the delay that I have found is in my patch. I think a better solution would be to split the radio control and the GUI parts of the program, but I am afraid that would require a major redesign of some parts of the program.

Anyway, this was a minor quick fix probably not worth keeping without keeping the other changes.

**Comment by jeffreydoran** [comment]
Would it stand to reason that the Pure Signal sample rate is "hard coded" to 192K (by ps_rate) for DDC0 and DDC1, evidently this is where the PS heavy lifting is performed? Meaning, whatever sample rate the GUI operator chooses for DDC2 and DDC3 (RX1 and RX2), has no real impact on Pure Signal performance? I believe there is a misconception in the user community, that they are "hurting pure signal" by running higher sample rates (> 192k) on RX1 and RX2 (DDC2/DDC3) 
Jeff NJ2US

**Comment by w-u-2-o** [comment]
Probably beating a dead horse at this point but there is absolutely no
reason to support PS sample rates in excess of 192KHz. Since separate DDCs
are used for PS, they are centered on the TX signal, and the TX signal
limited to 10KHz max. bandwidth, higher sample rates are not required.

Cheers!

Scott/w-u-2-o

**Comment by pavel-demin** [comment]
Thank you all for all the feedback. I now have enough new information about Thetis to start thinking about a better way to make my emulation of the HPSDR protocol more compatible with Thetis. Closing this pull request.

**Pull request closed without merging**
